### ISSUE TITLE
1801线路板滤芯寄存器地址及计算方法

### ISSUE THREAD

**Issue by yaomenglan** [seekteam/modbusRegister#2]
在开发cls4.0s控制器时，屏的软件工程师咨询滤芯的使用寿命是写在哪个寄存器内的？以及屏可以写入和读取滤芯寿命，这个用的是那个寄存器地址？我们公司提供的通讯协议内有关滤芯的寄存器地址有4个

**Comment by KrogeChen** [comment]
|Address|Name                     |R/W|Description                                                                                                  |
|-------|-------------------------|---|-----------------------------------------------------------------------------------------------------------|
|0x222C |粗效过滤网更换周期       |R/W|INT16U,0x0010 表示: 当前滤网更换周期为16天                                                                   |
|0x222D |中效过滤网更换周期       |R/W|                                                                                                             |
|0x222E |高校过滤网更换周期       |R/W|                                                                                                             |
|                        |
|0x2233 |粗效过滤网使用时间       |R/W|INT16U,0x0020 表示: 当前滤网已使用32天,写入只能是0x0000，其他数据忽略                                        |
|0x2234 |中效过滤网使用时间       |R/W|                                                                                                             |
|0x2235 |高效过滤网使用时间       |R/W|                                                                                                             |

上述寄存器是关于滤芯的更换周期和使用时间，文件已经描述的非常清楚。

**Comment by KrogeChen** [comment]
剩余使用寿命需要软件计算，（ 更换周期-使用时间）

**Comment by yaomenglan** [comment]
陈总监，您好，我想问下，当我想2233寄存器内写入时，是否只能写01 06 2233 0000？输入这个代码后返回的是什么代码，线路板是什么信息？

**Comment by KrogeChen** [comment]
是的，只能清零操作，代码是什么需要你自己试验一下，没法给你现成的答案。
